---
- name: Install and configure Zabbix Agent on RHEL-based systems
  hosts: SO              # أو all أو أي Group عندك في الـ Inventory
  become: true
  become_method: sudo

  vars:
    # عدّل IP حسب عنوان الـ Zabbix Server عندك
    zabbix_server: 192.168.10.246

    zabbix_agent_conf: /etc/zabbix/zabbix_agentd.conf

    # رابط الريبو حسب نسخة RHEL (هنا RHEL 9 / Rocky 9 / Alma 9)
    zabbix_repo_rpm: "https://repo.zabbix.com/zabbix/7.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-7.0-2.el{{ ansible_distribution_major_version }}.noarch.rpm"

  tasks:

    - name: Install Zabbix Repo RPM (with GPG check disabled)
      yum:
        name: "{{ zabbix_repo_rpm }}"
        state: present
        disable_gpg_check: yes

    - name: Install Zabbix Agent package
      yum:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Configure "Server" in zabbix_agentd.conf
      lineinfile:
        path: "{{ zabbix_agent_conf }}"
        regexp: '^Server='
        line: "Server={{ zabbix_server }}"
        backup: yes

    - name: Configure "ServerActive" in zabbix_agentd.conf
      lineinfile:
        path: "{{ zabbix_agent_conf }}"
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server }}"

    - name: Set Hostname to inventory_hostname
      lineinfile:
        path: "{{ zabbix_agent_conf }}"
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"

    - name: Enable and start Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started
