---
- name: Install Zabbix Agent on RHEL-based systems
  hosts: all
  become: true
  gather_facts: yes

  vars:
    zabbix_version: "7.0"
    zabbix_repo_base: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}"
    zabbix_rhel_major: "{{ ansible_distribution_major_version }}"

  tasks:

    - name: Debug system info (just once)
      debug:
        msg: "Host {{ inventory_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
      run_once: false

    - name: Install Zabbix repo (RHEL 8)
      yum:
        name: "{{ zabbix_repo_base }}/rhel/8/x86_64/zabbix-release-{{ zabbix_version }}-2.el8.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when:
        - ansible_os_family == "RedHat"
        - zabbix_rhel_major | int == 8

    - name: Install Zabbix repo (RHEL 9)
      yum:
        name: "{{ zabbix_repo_base }}/rhel/9/x86_64/zabbix-release-{{ zabbix_version }}-2.el9.noarch.rpm"
        state: present
        disable_gpg_check: yes
      when:
        - ansible_os_family == "RedHat"
        - zabbix_rhel_major | int == 9

    - name: Install Zabbix Agent package
      yum:
        name: zabbix-agent
        state: present
      when: ansible_os_family == "RedHat"

    - name: Configure "Server" in zabbix_agentd.conf
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=192.168.10.150'
        backup: yes
      notify: Restart zabbix agent
      when: ansible_os_family == "RedHat"

    - name: Configure "ServerActive" in zabbix_agentd.conf
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=192.168.10.150'
        backup: yes
      notify: Restart zabbix agent
      when: ansible_os_family == "RedHat"

    - name: Set Hostname to inventory_hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        backup: yes
      notify: Restart zabbix agent
      when: ansible_os_family == "RedHat"

    - name: Enable and start Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started
      when: ansible_os_family == "RedHat"

  handlers:
    - name: Restart zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted
