---
- name: Install Zabbix Agent on RHEL 9 servers
  hosts: fleet-node,manger-node        # غيّرها لو عندك group اسمه linux مثلاً
  become: yes

  tasks:
    - name: Disable securityonion repo if it exists
      ansible.builtin.shell: "sed -i 's/^enabled=1/enabled=0/' /etc/yum.repos.d/securityonion*.repo"
      args:
        warn: false
      ignore_errors: yes

    - name: Clean dnf cache
      ansible.builtin.command: dnf clean all
      register: dnf_clean
      changed_when: false

    - name: Install Zabbix repository package (RHEL 9)
      ansible.builtin.dnf:
        name: "https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm"
        state: present
        disable_gpg_check: true

    - name: Make sure Zabbix repos metadata is up to date
      ansible.builtin.command: dnf makecache
      changed_when: false

    - name: Install Zabbix agent
      ansible.builtin.dnf:
        name: zabbix-agent
        state: present

    - name: Enable and start Zabbix agent service
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started
        enabled: yes
